# Generated by Django 3.2.17 on 2023-02-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20230220_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'verbose_name_plural': 'Voucher'},
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.IntegerField(choices=[(1, 'percent'), (2, 'Fixed')]),
        ),
    ]
